---
snmp:
    snmp_community: "gh-lab"

ospf:
    ospf_rid: 12.12.12.12
    ospf_process: "1"
    ospf_networks:
        - ip: "0.0.0.0"
          wildcard: "255.255.255.255"
          area: "0"

bgp: 
    asn: "65001"
    rid: 12.12.12.12
    update_source: "loopback0"
    route_reflector: False
    neighbors:
       - 3.3.3.3
       - 4.4.4.4

loopback0: "12.12.12.12"